# config/services.yaml

parameters:
  # Puedes definir parámetros globales aquí si los necesitas

services:
  _defaults:
    autowire: true      # Symfony intentará inyectar automáticamente las dependencias requeridas
    autoconfigure: true # Symfony registrará automáticamente servicios como comandos, eventos, etc.

  # Registro automático de todos los servicios (controladores, repositorios, servicios, etc.)
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Asegúrate de que Symfony pueda encontrar tus controladores correctamente
  # Simplemente registramos la carpeta de los controladores sin necesidad de 'type: attribute'
  App\Controller\:
    resource: '../src/Controller/'
    exclude:
      - '../src/Controller/SomeExcludedController.php' # Si deseas excluir algunos controladores específicos
